---
identify: &httpCommon
  param: uid
  cookieMaxAge: <%= 3 * 365 * 24 * 60 * 60 %>
http: &http
  host: <%= env.HOST || '0.0.0.0' %>
  port: <%= env.PORT || '8080' %>
websocket:
  https:
    <<: *http
    certFile: /Users/user/projects/certificates/rockstat.test.crt
    keyFile: /Users/user/projects/certificates/rockstat.test.key
    port: <%= env.PORT_WSS || '8083' %>
  path: /wss
  perMessageDeflate:  # See zlib defaults.
    zlibDeflateOptions:
      chunkSize: 1024
      memLevel: 7
      level: 3
    zlibInflateOptions:
      chunkSize: <%= 10 * 1024 %>
    # Other options settable:
    clientNoContextTakeover: true # Defaults to negotiated value.
    serverNoContextTakeover: true  # Defaults to negotiated value.
    clientMaxWindowBits: 10       # Defaults to negotiated value.
    serverMaxWindowBits: 10       # Defaults to negotiated value.
    # Below options specified as default values.
    concurrencyLimit: 10          # Limits zlib concurrency for perf.
    threshold: 1024               # Size (in bytes) below which messages
    # should not be compressed.

rpc:
  name: kernel

redis:
  url: <%= env.REDIS_URL || 'redis://127.0.0.1:6379' %>
  db: 0
log:
  use: pino
  pino:
    name: alco
    safe: true
    level: <%= env.LOG_LEVEL || 'info' %>
    prettyPrint: false

client: {} # do not remove. root element should be present

browserLib:
  prod:
    file: clientlib/lib.js
  dev:
    file: clientlib/lib-dev.js

